### PR TITLE
travis: update node_js to 7

### PR DESCRIPTION
**Pull request by JLHwung**

### CODE REVIEW

**Review by maxknee — APPROVED** [review]
Looks good to me.
Add reminder to remove `v4` in October

**Comment by maxknee** [comment]
@JLHwung  https://github.com/maxknee/hexo-render-pug/releases/tag/v1.1.0

**Comment by JLHwung** [comment]
@maxknee Thanks. Should we use greenkeeper to keep dependencies up-to-date?

**Comment by maxknee** [comment]
@JLHwung I dont think so, it could introduce bugs unknowingly and I would rather test it prior to just blindly updating.

**Comment by JLHwung** [comment]
@maxknee Does travis suffice to test? If so we can try green keeper who merely raises pull request to update dependencies. It still depends on human to merge that.

**Pull request merged**
